import type { Listing } from "./models";

export const mockListings: Listing[] = [
  {
    id: "l4",
    title: "Aurora Retreat",
    description:
      "A sanctuary with timeless design and exceptional craftsmanship to inspire your next chapter.",
    location: "Banana Island, Lagos",
    pricePerNight: 3500000,
    currency: "NGN",
    rooms: 5,
    bathrooms: 6,
    type: "House",
    images: [
      "https://picsum.photos/seed/bluerock-l4-1/1200/800",
      "https://picsum.photos/seed/bluerock-l4-2/1200/800",
      "https://picsum.photos/seed/bluerock-l4-3/1200/800",
    ],
    amenities: ["Infinity pool", "Chef kitchen", "Cinema room", "24/7 security", "Ocean view"],
    rules: ["No smoking", "No parties", "ID required"],
    featured: true,
    host: { name: "Shahzaib Ahmad", phone: "+2348011111111", email: "aurora@bluerock.com" },
    availabilityNote: "Premium stay with concierge support.",
  },
  {
    id: "l5",
    title: "Palmview Estate",
    description:
      "Cinematic showcase for tropical living with soft curves and warm ambient light.",
    location: "Epe, Lagos",
    pricePerNight: 1500,
    currency: "USD",
    rooms: 4,
    bathrooms: 4,
    type: "House",
    images: [
      "https://picsum.photos/seed/bluerock-l5-1/1200/800",
      "https://picsum.photos/seed/bluerock-l5-2/1200/800",
      "https://picsum.photos/seed/bluerock-l5-3/1200/800",
    ],
    amenities: ["Pool deck", "Smart lighting", "Private cinema", "Chef service"],
    rules: ["No pets", "No events"],
    featured: true,
    host: { name: "Adaeze K.", phone: "+2348022222222", email: "palmview@bluerock.com" },
    availabilityNote: "Best for destination stays and weekend retreats.",
  },
  {
    id: "l6",
    title: "Harbor Glass Loft",
    description:
      "Minimal waterfront loft with wall-to-wall glazing and an open entertaining layout.",
    location: "Victoria Island, Lagos",
    pricePerNight: 220000,
    currency: "NGN",
    rooms: 2,
    bathrooms: 2,
    type: "Apartment",
    images: [
      "https://picsum.photos/seed/bluerock-l6-1/1200/800",
      "https://picsum.photos/seed/bluerock-l6-2/1200/800",
    ],
    amenities: ["High-speed Wi-Fi", "Waterfront balcony", "Elevator access", "Backup power"],
    rules: ["No smoking"],
    host: { name: "Tomi A.", email: "harbor@bluerock.com" },
    availabilityNote: "Popular with business travelers.",
  },
  {
    id: "l7",
    title: "The Courtyard Villa",
    description:
      "An airy family villa centered around a private courtyard garden and pool.",
    location: "Asokoro, Abuja",
    pricePerNight: 280000,
    currency: "NGN",
    rooms: 4,
    bathrooms: 5,
    type: "House",
    images: [
      "https://picsum.photos/seed/bluerock-l7-1/1200/800",
      "https://picsum.photos/seed/bluerock-l7-2/1200/800",
      "https://picsum.photos/seed/bluerock-l7-3/1200/800",
    ],
    amenities: ["Private pool", "Garden lounge", "Security", "Housekeeping"],
    rules: ["No parties", "Quiet hours after 10pm"],
    featured: true,
    host: { name: "BlueRock Signature Host", phone: "+2348033333333" },
    availabilityNote: "Longer stays receive discounted rates.",
  },
  {
    id: "l8",
    title: "Skyline Nest",
    description:
      "Compact luxury apartment with skyline views, warm oak finishes, and spa-style bath.",
    location: "Kilimani, Nairobi",
    pricePerNight: 240,
    currency: "USD",
    rooms: 1,
    bathrooms: 1,
    type: "Apartment",
    images: [
      "https://picsum.photos/seed/bluerock-l8-1/1200/800",
      "https://picsum.photos/seed/bluerock-l8-2/1200/800",
    ],
    amenities: ["Rooftop gym", "Workspace", "24/7 reception"],
    rules: ["No pets"],
    host: { name: "Lilian M.", email: "skyline@bluerock.com" },
    availabilityNote: "Ideal for solo trips and city breaks.",
  },
  {
    id: "l9",
    title: "Savana Ridge Home",
    description:
      "A warm contemporary home with broad terraces and sunset views over the ridge.",
    location: "Enugu",
    pricePerNight: 98000,
    currency: "NGN",
    rooms: 3,
    bathrooms: 3,
    type: "House",
    images: [
      "https://picsum.photos/seed/bluerock-l9-1/1200/800",
      "https://picsum.photos/seed/bluerock-l9-2/1200/800",
    ],
    amenities: ["Terrace", "Generator", "Smart TV", "Parking"],
    rules: ["No smoking indoors"],
    host: { name: "Emeka O." },
    availabilityNote: "Family-friendly and quiet neighborhood.",
  },
  {
    id: "l10",
    title: "Marina Pearl Residences",
    description:
      "Polished seafront apartment with soft neutral interiors and hotel-grade comfort.",
    location: "Oniru, Lagos",
    pricePerNight: 185000,
    currency: "NGN",
    rooms: 2,
    bathrooms: 2,
    type: "Apartment",
    images: [
      "https://picsum.photos/seed/bluerock-l10-1/1200/800",
      "https://picsum.photos/seed/bluerock-l10-2/1200/800",
      "https://picsum.photos/seed/bluerock-l10-3/1200/800",
    ],
    amenities: ["Sea view", "Concierge", "Gym", "Washer"],
    rules: ["No parties", "Government ID required"],
    featured: true,
    host: { name: "Mariam F.", phone: "+2348044444444" },
    availabilityNote: "Often booked weeks in advance.",
  },
  {
    id: "l1",
    title: "Modern 2BR Apartment",
    location: "Lekki, Lagos",
    pricePerNight: 85000,
    currency: "NGN",
    rooms: 2,
    bathrooms: 2,
    type: "Apartment",
    images: [
      "https://picsum.photos/seed/bluerock-l1-1/1200/800",
      "https://picsum.photos/seed/bluerock-l1-2/1200/800",
      "https://picsum.photos/seed/bluerock-l1-3/1200/800",
    ],
    amenities: ["Wi-Fi", "Kitchen", "Air conditioning", "Parking", "Security"],
    host: { name: "BlueRock Host" },
    availabilityNote: "Available most days. Minimum 2 nights.",
  },
  {
    id: "l2",
    title: "Cozy 3BR House with Garden",
    location: "Ikeja, Lagos",
    pricePerNight: 120000,
    currency: "NGN",
    rooms: 3,
    bathrooms: 3,
    type: "House",
    images: [
      "https://picsum.photos/seed/bluerock-l2-1/1200/800",
      "https://picsum.photos/seed/bluerock-l2-2/1200/800",
      "https://picsum.photos/seed/bluerock-l2-3/1200/800",
    ],
    amenities: ["Wi-Fi", "Washer", "Garden", "Parking"],
    host: { name: "Kehinde S." },
    availabilityNote: "Weekend availability is limited.",
  },
  {
    id: "l3",
    title: "Studio Apartment (City View)",
    location: "Victoria Island, Lagos",
    pricePerNight: 65000,
    currency: "NGN",
    rooms: 1,
    bathrooms: 1,
    type: "Apartment",
    images: [
      "https://picsum.photos/seed/bluerock-l3-1/1200/800",
      "https://picsum.photos/seed/bluerock-l3-2/1200/800",
    ],
    amenities: ["Wi-Fi", "Air conditioning", "Gym access"],
    host: { name: "BlueRock Host" },
    availabilityNote: "Great for short stays.",
  },
];
